# Generated by Django 5.2.7 on 2025-11-09 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_propiedad', models.CharField(max_length=50)),
                ('superficie_total', models.FloatField(blank=True, null=True)),
                ('superficie_cubierta', models.FloatField(blank=True, null=True)),
                ('ambientes', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasaciones_como_agente', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasaciones_como_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenTasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tasaciones/imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('tasacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tasaciones.tasacion')),
            ],
        ),
    ]
