# Generated by Django 5.2.7 on 2025-11-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='agentes/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(unique=True)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('localidad', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('alquiler_temporario', 'Alquiler Temporario')], max_length=30)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('lote', 'Lote'), ('local', 'Local Comercial'), ('campo', 'Campo'), ('quinta', 'Quinta'), ('ph', 'PH')], max_length=30)),
                ('descripcion', models.TextField()),
                ('orientacion', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(max_length=100)),
                ('superficie_total', models.FloatField()),
                ('superficie_cubierta', models.FloatField(blank=True, null=True)),
                ('ambientes', models.IntegerField()),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banios', models.IntegerField(blank=True, null=True)),
                ('cochera', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida / Alquilada')], default='disponible', max_length=30)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='Inmobiliaria.agente')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('destacada', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Inmobiliaria.propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='Inmobiliaria.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='Inmobiliaria.propiedad')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
