# Generated by Django 5.2.7 on 2025-11-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_propiedad', models.CharField(max_length=50)),
                ('superficie_total', models.FloatField(blank=True, null=True)),
                ('superficie_cubierta', models.FloatField(blank=True, null=True)),
                ('ambientes', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasaciones', to='Inmobiliaria.cliente')),
            ],
        ),
    ]
