# Generated by Django 5.2.7 on 2025-11-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0002_tasacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='es_tasador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasacion',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasaciones', to='Inmobiliaria.agente'),
        ),
        migrations.CreateModel(
            name='ImagenTasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tasaciones/imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('tasacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Inmobiliaria.tasacion')),
            ],
        ),
    ]
